name: actilink

packages:
  - apps/*
  - packages/*
    
scripts:
  lint:
    run: melos format --set-exit-if-changed && melos analyze --fatal-warnings
    
  dart:test:
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      flutter: false
      
  flutter:test:
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      
  test:
    steps:
      - melos run dart:test
      - melos run flutter:test

  generate:
    run: dart run build_runner build
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: [build_runner, freezed]

  dev:
    exec: flutter run --flavor development --target lib/main_development.dart
    packageFilters:
      scope: actilink

  stage:
    exec: flutter run --flavor staging --target lib/main_staging.dart
    packageFilters:
      scope: actilink

  prod:
    exec: flutter run --flavor production --target lib/main_production.dart
    packageFilters:
      scope: actilink

  build:android:apk:
    exec: flutter build apk --flavor development --target lib/main_development.dart
    packageFilters:
      scope: actilink

  build:android:bundle:
    exec: flutter build appbundle --flavor development --target lib/main_development.dart
    packageFilters:
      scope: actilink
      
command:
  clean:
    hooks:
      post: melos exec --flutter --concurrency=3 -- "flutter clean"

