import 'package:actilink/models/event.dart';

final List<Event> sampleEvents = [
  Event(
    eventId: 1,
    organizerId: 10,
    title: "Weekend Tennis Meetup",
    startTime: DateTime.parse("2025-05-10T14:00:00Z"),
    endTime: DateTime.parse("2025-05-10T18:00:00Z"),
    venue: "City Tennis Courts",
    location: "Warsaw",
    price: 25.0,
    maxUsers: 4,
    minUsers: 2,
    description:
        "Let's play some casual doubles tennis! Open to all skill levels.",
    user: 'John Johnson',
    relatedHobbies: ['Tennis', 'Sports', 'Outdoor'],
  ),
  Event(
    eventId: 2,
    organizerId: 11,
    title: "Open Mic & Jam Session",
    startTime: DateTime.parse("2025-06-01T19:00:00Z"),
    endTime: DateTime.parse("2025-06-01T22:00:00Z"),
    venue: "Underground Club",
    location: "Krakow",
    price: 0.0,
    maxUsers: 30,
    minUsers: 5,
    description:
        "Bring your instrument or your voice – join us for a chill music jam!",
    user: 'Daisy Hall',
    relatedHobbies: ['Music', 'Singing', 'Guitar'],
  ),
  Event(
    eventId: 3,
    organizerId: 12,
    title: "Morning Yoga by the Sea",
    startTime: DateTime.parse("2025-07-03T07:30:00Z"),
    endTime: DateTime.parse("2025-07-03T08:30:00Z"),
    venue: "Beach Zone 3",
    location: "Gdansk",
    price: 10.0,
    maxUsers: 20,
    minUsers: 3,
    description:
        "Start the day with mindful movement and sea breeze. Beginners welcome!",
    user: "Molly Ford",
    relatedHobbies: ['Yoga', 'Wellness', 'Outdoor'],
  ),
  Event(
    eventId: 4,
    organizerId: 13,
    title: "Board Game Night",
    startTime: DateTime.parse("2025-05-18T18:00:00Z"),
    endTime: DateTime.parse("2025-05-18T22:00:00Z"),
    venue: "Geek Cafe",
    location: "Poznan",
    price: 5.0,
    maxUsers: 12,
    minUsers: 4,
    description:
        "Bring your favorite games or try ours! Friendly and chill crowd.",
    user: "Tomasz Kowalski",
    relatedHobbies: ['Board Games', 'Strategy', 'Social'],
  ),
  Event(
    eventId: 5,
    organizerId: 14,
    title: "Running Group – Sunday 10K",
    startTime: DateTime.parse("2025-05-21T08:00:00Z"),
    endTime: DateTime.parse("2025-05-21T09:00:00Z"),
    venue: null,
    location: "Wroclaw",
    price: 0.0,
    maxUsers: 10,
    minUsers: 2,
    description:
        "10km light run around the park. Pace: ~5:30/km. Coffee after?",
    user: "Alex Nowak",
    relatedHobbies: ['Running', 'Fitness', 'Outdoor'],
  ),
];
