name: Setup environment
description: Setup environment for Flutter project

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "21.x"
        cache: gradle

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.29.1
        channel: "stable"
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
        architecture: x64

    - name: Install Melos
      uses: bluefireteam/melos-action@v3

    - name: Install dependencies and link packages
      run: melos bootstrap
      shell: bash
