name: CI

on: [ push ]

jobs:
  flutter_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare_env

      - name: Verify formatting and analyze
        run: melos run lint


  flutter_test:
    name: Test
    needs: flutter_lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare_env

      - name: Run tests
        run: melos run test
